# Generated by Django 4.1.7 on 2023-03-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_category_image_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, upload_to='shop/static/pic'),
        ),
    ]
