# Generated by Django 4.1.7 on 2023-03-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_img_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_img',
            options={'verbose_name': 'Фото продукта', 'verbose_name_plural': 'Фото продуктов'},
        ),
        migrations.AlterField(
            model_name='product_img',
            name='category',
            field=models.IntegerField(),
        ),
    ]
