# Generated by Django 4.1.7 on 2023-03-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_img_options_alter_product_img_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_img',
            name='category',
        ),
    ]
