# Generated by Django 4.1.7 on 2023-03-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_product_img_remove_product_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='shop\\static\\shop\\prod_img')),
            ],
        ),
    ]
