# Generated by Django 4.0.6 on 2023-03-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_img',
            options={'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
        migrations.AddField(
            model_name='product',
            name='imgg',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
