# Generated by Django 4.0.6 on 2023-03-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_img_imgg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_img',
            name='imgg',
        ),
        migrations.AlterField(
            model_name='product',
            name='imgg',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product_img'),
        ),
    ]
